88 refacto error message
Zenika/OZKOUR pull request #89
Opened 2022-07-21 09:38 UTC by reibecca

Le message d'erreur affiché quand un visuel ne peut pas être générer n'était pas tres visible.
Ajout d'une image et message mis en superposition au reste des éléments au centre de l'écran de l'utilisateur.

2022-07-21 10:05 UTC, Pranxtor requested changes

2022-07-21 10:05 UTC, Pranxtor commented on ozkour-front/src/views/TalkForm.vue
> +      <img
C'est pas mieux d'utiliser une svg plutôt qu'une img?

2022-07-21 16:08 UTC, aceol commented on ozkour-front/src/views/TalkForm.vue
> +      isErrorMessageVisible: true
A supprimer (ou utiliser à la place de `isSlidesGenerationFailed`)

2022-07-21 16:09 UTC, aceol approved these changes

2022-07-25 08:47 UTC, BK-sensei commented on ozkour-front/src/views/TalkForm.vue
> +      <img
Vu qu'il s'agit d'un petit element, c'est pas obligatoire de mettre un svg (surtout que ce pictogramme n'est pas disponible sous ce format dans le kit marketing)

2022-07-26 13:30 UTC, Pranxtor approved these changes

2022-07-26 13:32 UTC, merged